### PR TITLE
Some bug fixes with dynamic analysis

### PR DESCRIPTION
**Pull request by jefenux99**
Hi Ajin,

Here are some changes I have applied for setting up dynamic analysis on Android 5.1.1.

### CODE REVIEW

**Comment by ajinabraham** [comment]
@jefenux99 This doesn't add support for Android versions >4.4
Currently the script only supports Android 4.03 - 4.4.

These are some challenges

* The Xposed Framework APK that comes with MobSF is compactible till Android 4.4
* Higher versions of Android API and OS doesn't always respect the proxy you set for the WiFi Connection. 

Possible Fix
-----------
* Ask user for the version of Android OS in the VM/Device and based on the user choice install the exposed framework.
* Add a Copy of Xposed for Android >5 : http://forum.xda-developers.com/showthread.php?t=3034811
* Add some Xposed module / app that route all the web traffic through MobSF proxy. (I haven't looked into this much)

**Comment by jefenux99** [comment]
First of all, thanks for all the work you do on this matter, a lot of things that I did manually in the past, now I have no longer need to do thanks to this great tool :)

Sorry for the confusion, I would like to clarify something: regardless the Android version of my device, I get an error while executing mobsfy.py or DynamicAnalyzer/views/android.py script when multiple devices are connected (Ex: a USB ADB connection and WiFi connection enabled at the same time). See attachment [mobsf.txt](https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/files/505063/mobsf.txt).

The second issue concerns the rootCA file permissions in Android devices.
After executing mobsf.py or DynamicAnalyzer/views/android.py script, the MobSEC RootCA doesn't appear in the OS certificate store list (Settings->Trusted credentials->SYSTEM)
All certificates in /system/etc/security/cacerts/ directory are set with 644 permissions.

I've reworded my previous commits for that, see here:
https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/pull/232/files

**Comment by jefenux99** [comment]
Regarding the challenge to add support for other Android versions, for now I've added temporarily the following check for my specific needs (I use the same physical device for MobSF and WebView debugging with Chrome):

```
-    XP = os.path.join(TOOLSDIR,'onDevice/Xposed.apk')
+    print "\n[INFO] Getting Android OS version"
+    getAndroidVersion = ExecuteCMD([adb, "-s",adbconnect ,"shell", "getprop", "ro.build.version.release"], ret =True)
+    AndroidVersion = getAndroidVersion.replace("\r\n","")
+    if AndroidVersion in ["4.3","4.4"]:
+        XP = os.path.join(TOOLSDIR,'onDevice/Xposed.apk')
+    elif AndroidVersion == "5.1.1":
+        XP = os.path.join(TOOLSDIR,'onDevice/XposedInstaller_3.0_alpha4.apk')
+    else:
+        print "\n[ERROR] Android " +str(AndroidVersion)+ " OS version not yet supported"
+        sys.exit(0)
```

and install ProxyOn APK (http://repo.xposed.info/module/mobi.acpm.proxyon).
I wrote another script to flash the Xposed framework on device.

I need to perform some tests to be sure if I am able to route all trafic (of my app) through PyWebProxy with this Xposed module. Thanks for this useful information.

**Comment by ajinabraham** [comment]
LGTM 👍

**Pull request merged**
